server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:lulo;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    # driverClassName: org.h2.Driver (Spring Boot lo detectará automáticamente)
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: "CHANGE_ME_SUPER_SECRET"
    expirationMinutes: 120
