# En self-hosting puedes usar stringData directamente.
# K8s codifica los valores en base64 internamente.
apiVersion: v1
kind: Secret
metadata:
  name: lulo-secrets
  namespace: proyectoweb
type: Opaque
stringData:
  POSTGRES_USER: "lulo_user"
  POSTGRES_PASSWORD: "G12@kL4$$Px8!Rt3#Qw9Z"
  SPRING_DATASOURCE_USERNAME: "lulo_user"
  SPRING_DATASOURCE_PASSWORD: "G12@kL4$$Px8!Rt3#Qw9Z"
  JWT_SECRET: "change_me_use_a_long_random_string"
  JWT_EXPIRATION_MINUTES: "120"
