name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build and analyze
        working-directory: lulo-starter/backend
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=proyectoweb-backend \
          -Dsonar.organization=samuelmontealegre \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
